Theme/Style Gatsby Frontend
last-train/website pull request #6
Opened 2020-09-30 04:38 UTC by tiakindele

2020-11-02 18:59 UTC, tiakindele commented
@dtoki Please review

2020-11-23 18:37 UTC, dtoki requested changes
LGTM 👍, Let's change the smemvar to `0.0.1`

2020-11-23 18:37 UTC, dtoki commented on package.json
>    "version": "1.0.0",
Let's change the version to 0.0.1? and follow smvar versioning rules. 
what do you think?

2020-11-23 18:55 UTC, dtoki approved these changes

2021-01-08 17:32 UTC, merged